### PR TITLE
Fix parent2 not in data when undefined, add constants file

### LINKED ISSUE #69: Parent2 not in data when undefined

### PR DESCRIPTION
**Pull request by tjomson**
resolves #69

### CODE REVIEW

File: parser/src/authorship.ts [hunk 1]
```diff
@@ -1,26 +1,24 @@
...
 export async function hydrateTreeWithAuthorship(
   repo: string,
   commit: GitCommitObject
 ) {
   let { hash: child, parent } = commit
 
   let isDone = false
-  while (isDone === false) {
-    if (parent === undefined) {
+  while (!isDone) {
```
Comment (joglr) [inline parser/src/authorship.ts:14]: Nice change!

**Review by joglr — APPROVED** [review]
